### ISSUE TITLE
[documentation] Missing reference publication

### ISSUE THREAD

**Issue by e-dinesh** [exapde/Exasim#16]
https://github.com/exapde/Exasim/tree/master/Documentation/AIAA_Journal_2021_OAT15A.pdf

**Comment by rloekvh** [comment]
@exapde can you add this back in to the Documentation folder? I don't seem to have this latest version on my machine. Thanks.

**Comment by exapde** [comment]
The paper is going to be published. I'll add it back.

**Comment by rloekvh** [comment]
Closed with #21
